### ISSUE TITLE
Bing API key

### ISSUE THREAD

**Issue by systemed** [balloob/JMapViewer#2]
The key used in https://github.com/balloob/JMapViewer/blob/master/org/openstreetmap/gui/jmapviewer/tilesources/BingAerialTileSource.java#L25 is the Potlatch 2 Bing API key and is intended for editing only - please don't use this for non-editing applications like JMapViewer.

**Comment by balloob** [comment]
Removed it in 2a5874db2554a0ca2012a337ea0548cb6d9e5242
